repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(market_sentiment_analyzer/ui_streamlit\.py|test/test_vader\.py|test/test_sentiment\.py|test/test_ingest\.py|test/test_ui_helpers\.py|test/test_plots\.py|test/test_public_api\.py|test/test_ui_streamlit\.py)$

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
