name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pre-commit

      - name: Pre-commit (if config present)
        uses: pre-commit/action@v3.0.1
        if: hashFiles('.pre-commit-config.yaml') != ''
        with:
          extra_args: --all-files

      - name: Ruff check (fallback if pre-commit not used)
        if: hashFiles('.pre-commit-config.yaml') == ''
        run: ruff check .

      - name: Black check (fallback if pre-commit not used)
        if: hashFiles('.pre-commit-config.yaml') == ''
        run: black --check .
